"""empty message

Revision ID: 5f8cb952d2ab
Revises: f9452ca088d2
Create Date: 2020-12-13 10:45:46.373336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8cb952d2ab'
down_revision = 'f9452ca088d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todo SET completed = False WHERE completed IS NULL;')
    op.alter_column('todo', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
